### ISSUE TITLE
phpinfoにアクセスできる問題

### ISSUE THREAD

**Issue by TNTSuperMan** [ogatomo21/share-tool#2]
https://share-tool.net/api/info/

というURLにアクセスするとPHPInfoが閲覧できてしまいます。
原因はおそらく[こちら(/api/info/index.php)](https://github.com/webfullsympathy/share-tool/blob/main/api/info/index.php)です。

消した方がいいと思います。
vercelのサーバー(?)とはいえ、これはよくないのでは？
[phpinfoは一般的に危険とされています。](https://colo-ri.jp/develop/2010/01/phpinfo.html)

**Comment by webfullsympathy** [comment]
ちゃんと動いているかのテストで意図的に入れていたのですがVercelは他のサーバーが落ちているときに別のサーバーにリクエストさせる機能があるのでいつもより遅い場合ユーザーに見てもらった方がいいと思います。

**Comment by TNTSuperMan** [comment]
> いつもより遅い場合ユーザーに見てもらった方がいいと思います。

これがよくわからないんですけどどういうことでしょうか？

あともしphpinfoから使える脆弱性を割り出されてしまったら
サイトが改ざんされてウイルスまみれになる可能性もありますよ？

まあVercelのサーバーですからしっかりしているでしょうけど...

**Comment by webfullsympathy** [comment]
ですから、Vercelは他のサーバーが落ちているときに別のサーバーにリクエストさせる機能があるのであえて残してます。

**Comment by TNTSuperMan** [comment]
攻撃者がVercelを落とさないようにしつつ脆弱性でサイトが改ざんされたらどうするのでしょうか？

(まあ、一度漏洩したphpinfoはどうにもならないしvercel-php自体のバージョンみたいな感じだとおもいますし)

**Comment by webfullsympathy** [comment]
サイトを改ざん？オープンソースですしローカル側にもGitはあるので大丈夫です。

**Comment by TNTSuperMan** [comment]
ちがいます、いったん流れを言います。
1. VercelにGitHubの内容がデプロイ(反映)される
2. Vercel内に独立したファイルがあってそれが公開されてる
3. 脆弱性でVercel内のファイル(公開されてる)が改ざんされる
4. 共有サービスを見ようとするとウイルスに感染したりうんたらかんたら...

**公開されてるサイトの内容が改ざんされるんです。**
サイトデータが消えるとかじゃなくてユーザーにリスクが渡るんです。
Vercelが改ざん対策している可能性もありますが、リスクを減らすためにももう一度お考え下さい。

**Comment by webfullsympathy** [comment]
あ、Vercelの元データ側の話ですね。やっぱりInfoは消しておきます。(他鯖のデータベースいじってる人に言われたくないですが)

**Comment by TNTSuperMan** [comment]
ご納得頂きありがとうございます。攻撃者の手にphpinfoが渡っていないといいです。

あと
> (他鯖のデータベースいじってる人に言われたくないですが)

ってなんですかね？
プロフの説明のことならYoutubeやGitHubの活動等を通じて様々なデータを
容赦なく大量にアップしてることへの自虐ネタなので勘違いのないようお願いします。

**Comment by webfullsympathy** [comment]
あれ？()いれたはずなのですが(ネタだとわかるように)
phpinfoはリリースすら書かずに入れたのでバレてないと思います。

**Comment by TNTSuperMan** [comment]
分かりました、ネタだったんですね、ありがとうございます。

あれ、デプロイ失敗してますよ？

**Comment by webfullsympathy** [comment]
vercel.jsonから消すの忘れてました。ご指摘ありがとうございます。

**Comment by TNTSuperMan** [comment]
デプロイ成功してますね、よかったです！！！！！
